name: wallet_app_flutter
description: Soulon Wallet Flutter App
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  qr_flutter: ^4.1.0
  flutter_tilt: ^3.0.3
  crypto: ^3.0.6
  get_it: ^7.7.0
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
